import type { Metadata } from "next";
import Link from "next/link";
import GuideTemplate from "@/components/guides/GuideTemplate";
import { GuideH2 as H2, GuideCode as Code } from "@/components/guides/prose";
import { getGuideBySlug } from "@/lib/guides-registry";
import { buildPageMetadata } from "@/lib/seo";

const guide = getGuideBySlug("uuid-v4-vs-v1-vs-v5")!;
export const metadata: Metadata = buildPageMetadata({
  title: guide.title,
  description: guide.description,
  path: `/guides/${guide.slug}`,
});

export default function UuidVersionsGuidePage() {
  return (
    <GuideTemplate guide={guide}>
      <p>
        &quot;Generate a UUID&quot; usually just means v4 by default, and most of the time
        that&apos;s the right call. But the version number isn&apos;t decoration — v1 and v5
        encode real information into the ID in ways v4 deliberately doesn&apos;t, and picking the
        wrong one can leak more than you meant to, or fail to give you the property you actually
        needed.
      </p>

      <H2>What a UUID is, underneath the version differences</H2>
      <p>
        Every UUID is a 128-bit value, formatted as 32 hex characters split into five groups
        (<Code>8-4-4-4-12</Code>). The whole point of the format is that independent systems can
        generate IDs without coordinating with each other and still not collide. How those 128
        bits get filled in is exactly what the version number decides.
      </p>

      <H2>v4: random, and almost always the right default</H2>
      <p>
        A v4 UUID is generated from a cryptographically secure random number generator. 122 of
        its 128 bits are genuinely random (the other 6 are fixed to mark the version and variant),
        which makes the odds of two v4 UUIDs ever colliding astronomically small — negligible at
        any scale a real system will actually reach. Because it&apos;s pure randomness, a v4 UUID
        reveals nothing about when or where it was generated. This is what most systems mean when
        they say &quot;UUID&quot; without qualification, and it&apos;s what our UUID Generator
        produces.
      </p>

      <H2>v1: timestamp and machine identity, encoded directly in</H2>
      <p>
        A v1 UUID embeds the current timestamp and the generating machine&apos;s MAC address (or a
        substitute identifier) directly into the value. That&apos;s genuinely useful for one
        thing: v1 UUIDs sort roughly chronologically, which v4&apos;s pure randomness can never
        do. It&apos;s also the reason v1 fell out of favor as a default — anyone holding a v1 UUID
        can extract approximately when it was created and a machine-identifying value, which is a
        real information leak most applications never intended to expose. It still shows up in
        legacy systems and some databases that specifically need that time-ordering property.
      </p>

      <H2>v5: deterministic, not random at all</H2>
      <p>
        A v5 UUID is generated by hashing a namespace identifier together with a name — a URL, a
        domain-scoped string, anything you can supply consistently — using SHA-1. The property
        that matters here isn&apos;t randomness, it&apos;s the opposite: the same namespace and
        name always produce the exact same UUID, every time, on any machine, with zero
        coordination required. That&apos;s valuable when you need a stable ID derived from
        something you already have — turning a URL into a consistent identifier without having to
        look up or store a mapping anywhere.
      </p>

      <H2>Which one to actually use</H2>
      <ul className="ml-5 list-disc space-y-2">
        <li>
          <strong className="text-[#14140F]">Default to v4</strong>{" "}
          for session tokens, database primary keys, request IDs — anything where you just need a
          unique identifier and nothing about it should be inferable from the value itself.
        </li>
        <li>
          <strong className="text-[#14140F]">Reach for v5</strong>{" "}
          when you need the same input to always deterministically produce the same UUID, without
          a database lookup.
        </li>
        <li>
          <strong className="text-[#14140F]">Avoid v1</strong>{" "}
          unless you specifically need chronological sortability and have accepted that the ID
          leaks a timestamp and a machine identifier — for most applications built today, that
          trade-off isn&apos;t worth it.
        </li>
      </ul>
      <p>
        Our{" "}
        <Link href="/tools/uuid-generator" className="font-medium text-[#4438CA] hover:underline">
          UUID Generator
        </Link>{" "}
        creates random v4 UUIDs instantly in your browser, one at a time or in a batch.
      </p>
    </GuideTemplate>
  );
}
