import {
  Table,
  Braces,
  Code2,
  Image as ImageIcon,
  FileText,
  Fingerprint,
  Hash,
  Binary,
  KeyRound,
  Regex,
  FileSearch,
  Type,
  CaseSensitive,
  Pilcrow,
  Lock,
  Palette,
  Clock,
  Link2,
  QrCode,
  Globe,
  type LucideIcon,
} from "lucide-react";

export const toolIcons: Record<string, LucideIcon> = {
  table: Table,
  braces: Braces,
  code: Code2,
  image: ImageIcon,
  "file-text": FileText,
  fingerprint: Fingerprint,
  hash: Hash,
  binary: Binary,
  "key-round": KeyRound,
  regex: Regex,
  "file-search": FileSearch,
  type: Type,
  "case-sensitive": CaseSensitive,
  pilcrow: Pilcrow,
  lock: Lock,
  palette: Palette,
  clock: Clock,
  link: Link2,
  "qr-code": QrCode,
  globe: Globe,
};
